on: [push]

jobs:
  push-changes-downstream:
    runs-on: ubuntu-latest
    name: A job to propogate changes
    steps:
      - name: Checkout test-repo
        uses: actions/checkout@v2
        with:
          repository: cmarche2ti/test-repo
      - name: Push a file to another repository
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "setup.py"
          destination_repo: "cmarche2ti/test-repo-2"
          destination_folder: ""
          destination_branch_create: "auto_update"
          user_email: "cmarche2ti@gmail.com"
          user_name: "cmarche2ti"
          commit_message: ""
      # - name: Checkout test-repo-2
      #   uses: actions/checkout@v2
      #   with:
      #     repository: cmarche2ti/test-repo-2
