on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@main
      - id: foo
        uses: actions/my-github-action@main
        with:
          who-to-greet: "Chris"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
